# Generated by Django 3.1.2 on 2024-02-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='archivo',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='fecha_subida',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='documento',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
